---
- hosts: all
  tasks:
  - name: Install all security, critical, rollup, and definition updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - DefinitionUpdates
      reboot: yes
      reboot_timeout: 3600